commonEnv:
  PGHOST: "you-secret-host"
  PGPORT: "you-secret-port"
  PGUSER: "you-secret-user"
  PGPASSWORD: 'you-secret-password'
  PGDATABASE: "you-secret-db"
  AzureAccount: "you-sercet-az_ac"
  AzureKey: "you-secret-key"
  AzureContainer: "you-secret-name-container"
services:
  api-gateway:
    namespace: you-ns-1
  auth-service:
    namespace: you-ns-2
  markers-service:
    namespace: you-ns-3
  user-management:
    namespace: you-ns-4
