{{- if .Values.services }}
{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ $svc.namespace | quote }}
type: Opaque
stringData:
  PGHOST: {{ $.Values.commonEnv.PGHOST | quote }}
  PGPORT: {{ $.Values.commonEnv.PGPORT | quote }}
  PGUSER: {{ $.Values.commonEnv.PGUSER | quote }}
  PGPASSWORD: {{ $.Values.commonEnv.PGPASSWORD | quote }}
  PGDATABASE: {{ $.Values.commonEnv.PGDATABASE | quote }}
  Azure-account: {{ $.Values.commonEnv.AzureAccount | quote }}
  Azure-key: {{ $.Values.commonEnv.AzureKey | quote }}
  Azure-container: {{ $.Values.commonEnv.AzureContainer | quote }}
{{- end }}
{{- end }}