# auth_service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: kolyaacr.azurecr.io/auth_service:latest

        ports:
        - containerPort: 8000
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGHOST
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGUSER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGPASSWORD
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGPORT
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGDATABASE