commonEnv:
  PGHOST: "you-secret-host"
  PGPORT: "you-secret-port"
  PGUSER: "you-secret-user"
  PGPASSWORD: 'you-secret-password'
  PGDATABASE: "you-secret-db"
  GOOGLE_CLIENT_ID: "you-secret-google-client-id"
  GOOGLE_CLIENT_SECRET: "you-secret-google-client-secret"
  GITHUB_CLIENT_ID: "you-secret-github-client-id"
  GITHUB_CLIENT_SECRET: "you-secret-github-client-secret"
  DockerContainer: "you-secret-name-container"
services:
  api-gateway:
    namespace: you-ns-1
  auth-service:
    namespace: you-ns-2
  booking-service:
    namespace: you-ns-3
  admin-service:
    namespace: you-ns-4
