# Production values для Loki
# Использование: helm install loki . -f production-values.yaml

# Увеличиваем ресурсы для production
loki:
  replicas: 2  # Для высокой доступности
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

# Настройки для production
config:
  limits_config:
    retention_period: 2160h  # 90 дней retention для production
    max_query_series: 500000
    max_query_parallelism: 64
    max_entries_limit_per_query: 10000
  
  compactor:
    compaction_interval: 5m  # Более частая компрессия
    retention_delete_worker_count: 300

# Настройки для высокой нагрузки
service:
  type: LoadBalancer
  port: 3100
  targetPort: 3100
  # Если нужен NodePort вместо LoadBalancer:
  # type: NodePort
  # nodePort: 31000
