commonEnv:
  secretName: db-credentials
  envKeys:
    - AZURE_STORAGE_ACCOUNT
    - AZURE_STORAGE_KEY
    - AzureContainer

secret:
  name: db-credentials

configMap:
  name: loki-config


loki:
  replicas: 1
  image:
    repository: "grafana/loki"
    tag: "2.8.2"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
service:
  type: LoadBalancer
  port: 3100
  targetPort: 3100

config:
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    ingester:
      wal:
        enabled: true
        dir: /var/loki/wal
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 0
    schema_config:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper
          object_store: azure
          schema: v12
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: azure
      azure:
        account_name: ${AZURE_STORAGE_ACCOUNT}
        account_key: ${AZURE_STORAGE_KEY}
        container_name: ${AzureContainer}
        max_retries: 3
        request_timeout: 30s
    limits_config:
      retention_period: 744h  # 31 days retention
      max_query_series: 100000
      max_query_parallelism: 32
      max_entries_limit_per_query: 5000
    compactor:
      working_directory: /var/loki/compactor
      shared_store: azure
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150


