# charts/monitoring/values.yaml

# 🔑 Секреты для проброса (их имена)
# Это список ключей, который используется циклом 'range' в Deployment
secretEnvKeys:
  - AZURE_STORAGE_ACCOUNT
  - AZURE_STORAGE_KEY
  - AzureContainer # Ключ, содержащий имя контейнера

# Конфигурация Loki
loki:
  image: grafana/loki:2.8.2
  replicaCount: 1
  serviceType: LoadBalancer 
  port: 3100
  secretName: db-credentials # Имя Kubernetes Secret, который вы деплоите
  
  # 🔑 Добавьте сюда список ключей, который ищет ваш шаблон
  secretEnvKeys:
    - AZURE_STORAGE_ACCOUNT
    - AZURE_STORAGE_KEY
    - AzureContainer
  
  storage:
    type: azure
    # ...