# k8s-manifests/argocd-apps/api-gateway-ingress-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-ingress
  namespace: argocd
spec:
  # 🚨 ИСПОЛЬЗУЕМ ВАШ ПРОЕКТ ПЛАТФОРМЫ
  project: minemap-platform 
  source:
    # ⚠️ УКАЖИТЕ ВАШ РЕПОЗИТОРИЙ
    repoURL: https://github.com/Loks228/argo-cd-k8s.git 
    targetRevision: HEAD 
    # 🚨 ПУТЬ К ПАПКЕ, ГДЕ ЛЕЖИТ ingress.yaml
    path: k8s-manifests/ingress 

  destination:
    server: https://kubernetes.default.svc
    # 🚨 ДЕПЛОЙ ТОЛЬКО В API-GATEWAY NAMESPACE
    namespace: api-gateway 
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true