# argocd-loki-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: minemap-monitoring
  source:
    path: charts/monitoring
    repoURL: https://github.com/Loks228/argo-cd-k8s.git 
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true