# argocd-promtail-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: minemap-infra # Используем привилегированный проект
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.17.0 # Используйте нужную вам версию
    chart: promtail
    helm:
      values: |
        rbac:
          create: true 
        serviceAccount:
          create: true
          name: promtail 
        config:
          clients:
            - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# argocd-loki-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: minemap-infra # Используем тот же привилегированный проект
  source:
    # 🔑 URL вашего репозитория с кастомным Helm-чартом
    repoURL: https://github.com/Loks228/argo-cd-k8s.git 
    targetRevision: HEAD
    # 🔑 Путь к папке, содержащей ваш чарт Loki
    path: charts/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
