apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: minemap-platform 
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.4
    helm:
      values: |
        installCRDs: true 
          
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
    
  ignoreDifferences:
  # 1. Игнорирование конфликта Role/RoleBinding
  - group: rbac.authorization.k8s.io
    kind: Role
    name: cert-manager-startupapicheck:create-cert
    namespace: cert-manager
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: cert-manager-startupapicheck:create-cert
    namespace: cert-manager
  # 🚨 2. Игнорирование конфликта Webhook (Новый блок)
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: cert-manager-webhook
    jsonPointers:
    - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
    jsonPointers:
    - /webhooks
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true