commonEnv:
  secretName: db-credentials
  envKeys:
    - PGHOST
    - PGUSER
    - PGPASSWORD
    - PGPORT
    - PGDATABASE
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - GITHUB_CLIENT_ID
    - GITHUB_CLIENT_SECRET
    - BASE_URL
    - FRONTEND_URL
services:
  api-gateway:
    name: api-gateway
    namespace: api-gateway
    replicas: 2
    image: docker.io/api_gateway:1.2.11
    port: 8000
    targetPort: 8000
    serviceType: LoadBalancer
    host: api.minemap.ua
    secretName: api-gateway-tls

  auth-service:
    namespace: auth-service
    replicas: 2
    image: docker.io/auth_service:1.2.12
    port: 8000
    targetPort: 8001
    serviceType: ClusterIP

  booking-service:
    namespace: booking-service
    replicas: 2
    image: docker.io/booking_service:1.1.7
    port: 8000
    targetPort: 8002
    serviceType: ClusterIP

  admin-service:
    namespace: admin-service
    replicas: 2
    image: docker.io/admin_service:1.1.7
    port: 8000
    targetPort: 8004
    serviceType: ClusterIP