apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.8.2
          args: ["-config.file=/etc/loki/config.yaml"]
          env:
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: loki-azure
                  key: AZURE_STORAGE_ACCOUNT
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-azure
                  key: AZURE_STORAGE_KEY
            - name: AzureContainer
              valueFrom:
                secretKeyRef:
                  name: loki-azure
                  key: AzureContainer
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
              readOnly: true
            - name: loki-wal
              mountPath: /var/loki/wal
            - name: loki-index
              mountPath: /var/loki/index
            - name: loki-cache
              mountPath: /var/loki/cache
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-wal
          emptyDir: {}
        - name: loki-index
          emptyDir: {}
        - name: loki-cache
          emptyDir: {}