apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: {{ .Values.loki.replicas | default 1 }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository | default "grafana/loki" }}:{{ .Values.loki.image.tag | default "2.8.2" }}"
          args:
            - "-config.expand-env=true"
            - "-config.file=/etc/loki/config.yaml"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort | default 3100 }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name | default "db-credentials" }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /var/loki
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configMap.name | default "loki-config" }}
        - name: data
          emptyDir: {}
