apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 3100 }}
      targetPort: {{ .Values.service.targetPort | default 3100 }}
      protocol: TCP
      name: http
  selector:
    app: loki
