apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: {{ .Values.loki.replicas | default 1 }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      serviceAccountName: loki-sa
      initContainers:
        - name: init-loki-config
          image: alpine:3.18
          command:
            - /bin/sh
            - -c
            - |
              set -e
              apk add --no-cache gettext
              mkdir -p /var/loki/config /var/loki/wal /var/loki/index /var/loki/cache /var/loki/compactor
              envsubst < /etc/loki/config.yaml > /var/loki/config/config.generated.yaml
          env:
{{- if .Values.commonEnv.secretName }}
{{- range $i, $key := .Values.commonEnv.envKeys }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.commonEnv.secretName }}
                  key: {{ $key }}
{{- end }}
{{- end }}
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
              readOnly: true
            - name: loki-config-generated
              mountPath: /var/loki/config
            - name: loki-wal
              mountPath: /var/loki/wal
            - name: loki-index
              mountPath: /var/loki/index
            - name: loki-cache
              mountPath: /var/loki/cache
            - name: loki-compactor
              mountPath: /var/loki/compactor
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          command:
            - /usr/bin/loki
            - -config.file=/var/loki/config/config.generated.yaml
          ports:
            - containerPort: {{ .Values.service.targetPort | default 3100 }}
          resources:
{{- if .Values.loki.resources }}
{{ toYaml .Values.loki.resources | indent 12 }}
{{- end }}
          livenessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort | default 3100 }}
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort | default 3100 }}
            initialDelaySeconds: 45
            periodSeconds: 10
          env:
{{- if .Values.commonEnv.secretName }}
{{- range $i, $key := .Values.commonEnv.envKeys }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.commonEnv.secretName }}
                  key: {{ $key }}
{{- end }}
{{- end }}
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
              readOnly: true
            - name: loki-config-generated
              mountPath: /var/loki/config
            - name: loki-wal
              mountPath: /var/loki/wal
            - name: loki-index
              mountPath: /var/loki/index
            - name: loki-cache
              mountPath: /var/loki/cache
            - name: loki-compactor
              mountPath: /var/loki/compactor
      volumes:
        - name: loki-config
          configMap:
            name: {{ .Values.configMap.name | default "loki-config" }}
        - name: loki-config-generated
          emptyDir: {}
        - name: loki-wal
          emptyDir: {}
        - name: loki-index
          emptyDir: {}
        - name: loki-cache
          emptyDir: {}
        - name: loki-compactor
          emptyDir: {}