apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter-ingress
  namespace: argocd
spec:
  # 🚨 ИСПОЛЬЗУЕМ ВАШ ПРОЕКТ ПЛАТФОРМЫ
  project: minemap-monitoring 
  source:
    # ⚠️ УКАЖИТЕ ВАШ РЕПОЗИТОРИЙ
    repoURL: https://github.com/Loks228/argo-cd-k8s.git 
    targetRevision: HEAD 
    # 🚨 ПУТЬ К ПАПКЕ, ГДЕ ЛЕЖИТ ingress.yaml
    path: k8s-manifests/ingress/node-exporter/

  destination:
    server: https://kubernetes.default.svc
    # 🚨 ДЕПЛОЙ ТОЛЬКО В node-exporter NAMESPACE
    namespace: node-exporter 
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true