# user_management_service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: user-management
spec:
  selector:
    app: user-management-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000