
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: api-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod # если используешь cert-manager для TLS
spec:
  tls:
    hosts: api.minemap.ua
      secretName: api-gateway-tls

  rules:
    host: "api.minemap.ua"
    http:
      paths:
        path: /
        pathType: Prefix
        backend:
        service:
        name: "api-gateway" 
            port:
              number: 8000
